# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'


stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:

      - task: NodeTool@0
        inputs:
          versionSpec: '16.x'
        displayName: 'Install Node.js 16.x'
        env:
          NODE_OPTIONS: --max_old_space_size=16384

      - task: Npm@1
        inputs:
          command: 'custom'
          workingDir: '$(Build.SourcesDirectory)'
          customCommand: 'install --legacy-peer-deps'
        displayName: 'Install Dependencies'
        env:
          NODE_OPTIONS: --max_old_space_size=16384
    
      - task: Npm@1
        inputs:
          command: 'custom'
          customCommand: 'run create-dynamic-bundles'
        displayName: 'create-dynamic-bundles for css issues'

      - task: Npm@1
        inputs:
          command: 'custom'
          customCommand: 'run build'
          workingDir: '$(Build.SourcesDirectory)'
        displayName: 'Building angular code'
        env:
          NODE_OPTIONS: --max_old_space_size=16384

      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: '$(Build.SourcesDirectory)/dist'
          includeRootFolder: false
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/dist.zip'
          replaceExistingArchive: true
        displayName: 'Archiving dist folder'


      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'
        displayName: 'Publishing artifacts to the CD Pipeline'
      
